### ISSUE TITLE
Lightstrip plus 2 and Screen Zone

### ISSUE THREAD

**Issue by PokoTom** [kershner/screenBloom#29] opened 2017-03-20 11:29 UTC
Hi,

I currently have troubles with the following set up:
- 2 Hue bloom (right and left ot the screen)
- 1 Lightstrip behind screen (middle)

When I settup the 2 blooms for right and left screen zone, it works
But screen zone doesn't work with the lightstrip.

If I run it without screen zone, everything works perfectly (but all the same colors at the same time of course)

I tried to setup different zones for the lighstrip, even using only the lightstrip and desactivate the other bulbs. I only get a bright white when I start (so I assume the connexion is OK) but no variation after that.
As soon as I desactivate the screen zone, it works fine.

So maybe the screenzone doesn't work at all only with the lightstrip ? I don't know anything about coding, can you help me with this trouble ?

Nice work overall, I love it !

Regards,

Thomas

**Comment by kershner** [comment] 2017-03-20 14:31
Hey Thomas,

Thanks for opening the issue.  I think this is related to [#20 ](https://github.com/kershner/screenBloom/issues/20).  There is a bug with zone mode where certain configurations of lights will throw a ZeroDivionError.  I added dumb handling in the last update to keep ScreenBloom from crashing, but haven't had time to fully dig into the problem just yet.

I'll keep both this and #20 open for now.

**Comment by kershner** [comment] 2017-08-27 19:56
Hey there -

Pretty sure I've narrowed down the cause of this issue and fixed it with [this commit](https://github.com/kershner/screenBloom/commit/995ea668a726c5a494cc77668bd81421d57c2494).  You can grab a new version from [screenbloom.com](http://www.screenbloom.com).

Closing for now, but please add another comment if you try the new version and still have the error and I will re-open the issue.

**Closed by kershner** 2017-08-27 19:56 UTC
